about_index:
   path: /a-propos
   controller: App\Controller\AboutController::index

homepage_index:
    path: /
    controller: App\Controller\HomepageController::index

projects_index:
    path: /projects
    controller: App\Controller\ProjectController::index